//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocal_loginserver.proto
namespace gprotocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_LOGINSERVER")]
  public partial class CS_LOGINSERVER : global::ProtoBuf.IExtensible
  {
    public CS_LOGINSERVER() {}
    
    private string _s_account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s_account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string s_account
    {
      get { return _s_account; }
      set { _s_account = value; }
    }
    private string _s_password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"s_password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string s_password
    {
      get { return _s_password; }
      set { _s_password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}